### PR TITLE
Milestone 1:docs

### PR DESCRIPTION
**Pull request by Murodjon000**
In this project we are to complete the following:
1.  Watch this video about Entity Relationship Diagram (ERD).
2. Watch this video about Primary and Foreign Keys.
3.   Create your own ERD. You can use an online tool to do that or draw it on the piece of paper and take a photo of it.
4.   Think about friendship and friendship requests. Small hint: try to use status of the friendship to tell if it is a request or confirmed friendship.
5.  Extra hint: keep profile image as a link to gravatar as storing files is a bit tricky in Heroku.
6. Put a file with your ERD in the docs directory in your repo.

### CODE REVIEW

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Changes Requested 💀 

Thank you for submitting Pull Request. You have done a  great job. Please make the changes requested below:

- [ ]  You have added linters but not working. Please resolve this issue. Please check if workflows working at https://github.com/IjayAbby/ror-social-scaffold/actions or not? 
- [ ] Please add a friendship table to the image. Friendship table must-have status or confirmed column.


Please request another review after changes have been made. 

Best,
Arslan (arslanbisharat on slack)

**Comment by Murodjon000** [comment]
Hi thanks for checking our code but in friendship table, we have status column if you see.

**Comment by arslanbisharat** [comment]
> Hi thanks for checking our code but in friendship table, we have status column if you see.

I am sorry i didn't see it because of screen size. I am really sorry for the trouble. 
Please request another code review when u resolve lintets

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Changes Requested 💀 

Thank you for submitting Pull Request. You have done a  great job. Please make the changes requested below:

- [ ]  You have added linters but not working. Please resolve this issue. Please check if workflows working at https://github.com/IjayAbby/ror-social-scaffold/actions or not? 

Please request another review after changes have been made. 

Best,
Arslan (arslanbisharat on slack)

**Pull request merged**
